insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);
insert into product(restock_count,stock_count) values(0,0);

insert into user(email, mobile_number) values("banissi@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii1@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii2@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii3@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii4@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii5@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii6@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii7@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii8@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii9@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");
insert into user(email, mobile_number) values("banisii10@naver.com", "01034118840");

insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 1, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 2, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 3, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 4, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 5, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 6, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 7, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 8, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 9, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 10, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 11, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 12, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 13, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 14, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 15, 1, now());
insert into product_user_notification(product_id, user_id, is_active, created_at) values(1, 16, 1, now());